version: "3"
services:
  api:
    command: sh -c "npm install && ./node_modules/.bin/gulp"
    ports:
      - "4001:4001"
    build:
      context: ../docker-web-api
    volumes:
      - ../docker-web-api/app:/app
      - ./images:/images
    environment:
      NODE_ENV: development

  nsfw:
    command: sh -c "pip install 'ptvsd==3.0.0' && python /opt/nsfw/nsfw.py"
    build:
      context: ../docker-nsfw
    ports:
      - "4002:4002"
    volumes:
      - ../docker-nsfw/nsfw:/opt/nsfw/
    environment:
      DEBUG: 1
      FLASK_DEBUG: 1

  driftnet:
    build:
      context: ../docker-driftnet
    volumes:
      - ../docker-driftnet/app:/app
