version: "3"
services:
  api:
    command: sh -c "npm install && ./node_modules/.bin/gulp"
    ports:
      - "4001:4001"
    build:
      context: ../docker-web-api
    volumes:
      - ../docker-web-api/app:/app
      - ./images:/images
    environment:
      NODE_ENV: development

  nsfw:
    build:
      context: ../docker-nsfw
    volumes:
      - ../docker-nsfw/nsfw:/opt/nsfw/

  driftnet:
    build:
      context: ../docker-driftnet
